# Generated by Django 4.0.5 on 2022-06-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recargo_interior',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Recargo Interior'),
        ),
    ]
