# Generated by Django 4.0.5 on 2022-06-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_recargo_interior'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='porcentaje_vv',
            field=models.DecimalField(decimal_places=2, default=75, max_digits=18, verbose_name='% Vendedor'),
        ),
    ]
