# Generated by Django 4.0.5 on 2022-06-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_porcentaje_vv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='porcentaje_vv',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='% Vendedor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='recargo_interior',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Recargo Interior'),
        ),
    ]
