# Generated by Django 4.0.5 on 2022-06-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_porcentaje_vv_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewrating',
            options={'ordering': ['rating']},
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='PVP'),
        ),
        migrations.AlterModelTable(
            name='reviewrating',
            table='Valoraciones',
        ),
    ]
