# Generated by Django 4.0.5 on 2022-06-27 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_reviewrating_options_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_name']},
        ),
        migrations.AlterModelOptions(
            name='reviewrating',
            options={'ordering': ['rating'], 'verbose_name': 'Valoracion', 'verbose_name_plural': 'Valoraciones'},
        ),
        migrations.AlterModelTable(
            name='product',
            table='Productos',
        ),
        migrations.AlterModelTable(
            name='reviewrating',
            table=None,
        ),
    ]
