# Generated by Django 4.0.5 on 2022-06-28 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_options_alter_reviewrating_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
