# Generated by Django 4.0.5 on 2022-06-28 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_name', '-created_date'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
