# Generated by Django 4.0.5 on 2022-06-28 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variantion_category', models.CharField(choices=[('Edicion', 'Edicion')], max_length=200, verbose_name='Variacion')),
                ('variation_value', models.CharField(max_length=200, verbose_name='Numero')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('is_active', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Variacion',
                'verbose_name_plural': 'Variaciones',
            },
        ),
    ]
