# Generated by Django 4.0.5 on 2022-06-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_variation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'Edicion', 'verbose_name_plural': 'Ediciones'},
        ),
        migrations.AddField(
            model_name='variation',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/products', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='variation',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Subtitulo'),
        ),
    ]
