# Generated by Django 4.0.5 on 2022-06-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_variation_options_variation_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(max_length=200, verbose_name='Edicion'),
        ),
    ]
