# Generated by Django 4.0.5 on 2022-06-28 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_variation_variation_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variantion_category',
            new_name='variation_category',
        ),
    ]
