# Generated by Django 4.0.5 on 2022-06-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_variantion_category_variation_variation_category'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='variation',
            constraint=models.UniqueConstraint(fields=('product', 'variation_value'), name='id_titulo_edicion'),
        ),
    ]
