# Generated by Django 4.0.5 on 2022-06-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_variation_id_titulo_edicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/products', verbose_name='Imagen'),
        ),
    ]
