# Generated by Django 4.0.5 on 2022-06-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_variation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('Edicion', 'Edicion')], default='Edicion', max_length=200, verbose_name='Variacion'),
        ),
    ]
