# Generated by Django 4.0.5 on 2022-07-18 17:07

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=computed_property.fields.ComputedIntegerField(compute_from='stock_total', editable=False, verbose_name='Stock'),
        ),
    ]
