# Generated by Django 4.0.5 on 2022-06-27 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['product'], 'verbose_name': 'Item de Carrito', 'verbose_name_plural': 'Items de Carrito'},
        ),
        migrations.AlterModelTable(
            name='cart',
            table='Carrito',
        ),
    ]
