# Generated by Django 4.0.5 on 2022-06-27 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-date_added'], 'verbose_name': 'Carrito', 'verbose_name_plural': 'Carritos'},
        ),
        migrations.AlterModelTable(
            name='cart',
            table=None,
        ),
    ]
