# Generated by Django 4.0.5 on 2022-07-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_variation_variation_category'),
        ('carts', '0003_alter_cart_options_alter_cart_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation', verbose_name='Variaciones'),
        ),
    ]
