# Generated by Django 4.0.5 on 2022-07-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_cartitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Id_Carrito'),
        ),
    ]
