# Generated by Django 4.0 on 2022-07-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_product_stock'),
        ('carts', '0015_alter_cart_cart_id_alter_cart_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.Variation', verbose_name='Edicion'),
        ),
    ]
