# Generated by Django 4.0.5 on 2022-06-27 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='Telefono')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='Ultimo login')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Administrador')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo')),
                ('is_superadmin', models.BooleanField(default=False, verbose_name='Superadmin')),
            ],
            options={
                'verbose_name': 'Cuenta de Usuario',
                'verbose_name_plural': 'Cuentas de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Distribuidora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Distribuidora')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo Distribuidora')),
                ('provincia', models.CharField(max_length=50, verbose_name='Provincia')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, upload_to='userprofile', verbose_name='Imagen de perfil')),
                ('numero_vendedor', models.IntegerField(blank=True, default='0', unique=True, verbose_name='Numero de vendedor')),
                ('nombre_vendedor', models.CharField(default='deposito', max_length=50, unique=True, verbose_name='Nombre de vendedor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
        migrations.CreateModel(
            name='Subcuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Codigo')),
                ('provincia', models.CharField(max_length=50, verbose_name='Provincia')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('observaciones', models.CharField(blank=True, max_length=250, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('distribuidora', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.distribuidora')),
            ],
        ),
    ]
