# Generated by Django 4.0.5 on 2022-06-27 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['date_joined'], 'verbose_name': 'Cuenta de Usuario', 'verbose_name_plural': 'Cuentas de Usuarios'},
        ),
    ]
