# Generated by Django 4.0.5 on 2022-07-08 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_subcuenta_distribuidora_alter_account_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Distribuidora')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo Distribuidora')),
                ('provincia', models.CharField(max_length=50, verbose_name='Provincia')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
            ],
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['date_joined'], 'verbose_name': 'Cuenta de Usuario', 'verbose_name_plural': 'Cuentas de Usuarios'},
        ),
        migrations.CreateModel(
            name='Subcuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Codigo')),
                ('provincia', models.CharField(max_length=50, verbose_name='Provincia')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('observaciones', models.CharField(blank=True, max_length=250, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('distribuidora', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.distribuidora')),
            ],
        ),
    ]
