# Generated by Django 4.0.5 on 2022-07-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userprofile_nombre_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nombre_vendedor',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Nombre de vendedor'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='numero_vendedor',
            field=models.IntegerField(blank=True, unique=True, verbose_name='Numero de vendedor'),
        ),
    ]
