# Generated by Django 4.0.5 on 2022-07-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_profile_orderproduct_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='addres_line_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección 2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.FloatField(default=0, verbose_name='IVA'),
        ),
    ]
