# Generated by Django 4.0.5 on 2022-07-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_addres_line_2_alter_order_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='addres_line_1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='addres_line_2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_note',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='payment',
        ),
        migrations.AddField(
            model_name='order',
            name='nombre_vendor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de vendedor'),
        ),
        migrations.AddField(
            model_name='order',
            name='numero_vendedor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero de vendedor'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
