# Generated by Django 4.0.5 on 2022-07-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_addres_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total'),
        ),
    ]
