# Generated by Django 4.0.5 on 2022-07-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='nombre_vendor',
            new_name='nombre_vendedor',
        ),
        migrations.AddField(
            model_name='order',
            name='order_note',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
