# Generated by Django 4.0.5 on 2022-07-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_nombre_vendor_order_nombre_vendedor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_note',
        ),
    ]
