# Generated by Django 4.0.5 on 2022-07-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_order_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='numero_pedido',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero de Pedido'),
        ),
    ]
