# Generated by Django 4.0.5 on 2022-07-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderproduct_numero_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Aceptado', 'Aceptado'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='New', max_length=50, verbose_name='Estado'),
        ),
    ]
