# Generated by Django 4.0.5 on 2022-07-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_order_number_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Nuevo'), ('Accepted', 'Aceptado'), ('Completed', 'Completado'), ('Cancelado', 'Cancelado')], default='New', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='numero_pedido',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Numero de Pedido'),
        ),
    ]
