# Generated by Django 4.0 on 2022-07-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_product_stock'),
        ('orders', '0014_alter_order_status_alter_orderproduct_numero_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='variation',
            field=models.ManyToManyField(blank=True, to='store.Variation', verbose_name='Variaciones'),
        ),
    ]
